#!/bin/bash
#upgrading script apple linux T2 Kernel

if [ $USER != root ]
then
sudo chmod 755 $0
sudo $0 $1
exit 0
fi

if [[ $1 != -v ]]
then
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/var/log/t2-kernel-update.log 2>&1
fi

set -e

cd /tmp

use_lts=false
lts_version=5.15

if [[ $use_lts != true ]]
then
latest=$(curl -sL https://github.com/t2linux/T2-Ubuntu-Kernel/releases/latest/ | grep "<title>Release" | awk -F " " '{print $2}' )
else
getkernelver=$(curl -sL https://github.com/t2linux/T2-Ubuntu-Kernel/releases | grep "{{ urlEncodedRefName }}" | grep -v "generic" | grep v${lts_version} | cut -d "{" -f 3 | cut -c 25- | head -1)
latest=${getkernelver::-76}
fi

if [[ ${#latest} = 7 ]]
then
latestkver=$(echo $latest | cut -d "v" -f 2 | cut -d "-" -f 1 | awk '{print $1".0-1"}')
latestk=$(echo $latest | cut -c 2- | cut -d "-" -f 1 | awk '{print $1".0-t2"}')
else
latestkver=$(echo $latest | cut -d "v" -f 2)
latestk=$(echo $latest | cut -c 2- | cut -d "-" -f 1 | awk '{print $1"-t2"}')
fi

currentk=$(uname -r)

if [ \( $latestk != $currentk \) ]; then
	
	curl -L https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/${latest}/linux-headers-${latestk}_${latestkver}_amd64.deb > headers.deb
	curl -L https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/${latest}/linux-image-${latestk}_${latestkver}_amd64.deb > image.deb

	if [ -f headers.deb -a -f image.deb ]; then
	#install
	echo "Installing new kernel $latest"
	apt install ./headers.deb
	apt install ./image.deb
	#shutdown -r 02:00 "reboot scheduled for the next 2am to update runnning kernel"
	rm -f headers.deb image.deb
	#uninstall old kernel
		if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]
		then
		dpkg -r linux-headers-$(uname -r)
		dpkg -r linux-image-$(uname -r)
		fi
	fi
else
echo "Kernel is up to date"
fi
